packages:
  - apps/*
  - packages/*
  - packages/data-access/*
  - packages/templates/*
  - libs/*
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - nx
  - sharp
  - unrs-resolver
ignoredBuiltDependencies:
  - '@parcel/watcher'
